dependencies:
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  image_picker: ^1.1.2
  lottie: ^3.1.2
  equatable: ^2.0.5
  flutter_chat_ui: ^1.6.13
  flutter_chat_types: ^3.6.2
  shared_preferences: ^2.2.2
  uuid: ^4.4.2
  vibration: ^2.0.1

description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: ^3.6.0
flutter:
  uses-material-design: true
name: lifevibes
publish_to: none
version: 1.0.0+1
